PROGPLAT_ARCH         =m0
PROGPLAT_TYPE         =exps1
PROGPLAT_PARAMS       =nothing
PROGPLAT_BOARD        =stm32f0
PROGPLAT_RUN_TIMEOUT  =6
__PROGPLAT_MUL_RUNS__ =10
__PROGPLAT_MEM_DEF_1__  =expmem_byte_to_word(0)

